"""
Django settings for django_work project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

https://levelup.gitconnected.com/getting-started-with-django-e6b444014f86
https://levelup.gitconnected.com/build-a-project-management-system-in-django-part-2-d9d0059b08d3
https://levelup.gitconnected.com/build-a-project-management-system-in-django-part-3-f7619c08ece3
https://github.com/essykings/django_teams/tree/main
"""

from pathlib import Path
import os
from datetime import timedelta
import mimetypes

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!4=(j&f&lym%2%e#xpv3-r3+=w9z%pt-(9qx^*2^rima2uzwzx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'projects',
    'users',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',

]

ROOT_URLCONF = 'django_work.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_work.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/assets/img/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/assets')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static') # New version of Django of code could be : BASE_DIR / 'static'

]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


"""
Private modification from Setting.py 
"""

CRISPY_TEMPLATE_PACK = 'bootstrap5'

LOGIN_REDIRECT_URL ='tasks'
LOGIN_URL ='login'


EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


#Security package :
SECURE_CONTENT_TYPE_NOSNIFF = True # X-Content-Type-Options: This header prevents the browser from interpreting files as a different MIME type than what is specified by the content type in the HTTP headers.
SECURE_BROWSER_XSS_FILTER = True # X-XSS-Protection: This header is used to configure the XSS (cross-site scripting) filter built into most browsers.
SECURE_HSTS_SECONDS = 2592000  # 1 month
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True #Strict-Transport-Security: This header ensures that your site is only accessed using HTTPS, which protects against man-in-the-middle attacks.
SECURE_SSL_REDIRECT = True  #SSL Redirect: Redirects all non-HTTPS requests to HTTPS (only use if you are sure your site will always be served over HTTPS).
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin' # Referrer Policy: Controls the amount of information sent along with the Referer header.





# check if web is live then debug is False
if os.getcwd() =='/app':
    DEBUG = False